### ISSUE TITLE
[BUG] Unable to get `front-end/demo_light` running

### ISSUE THREAD

**Issue by ericthomas1** [stanford-oval/storm#143]
**Describe the bug**
I followed the docs in `front-end/demo_light/README.md`, but still receive an error. Any help would be greatly appreciated.

**Instructions**:

```
1. Clone the STORM repo
2. `cd front-end/demo_light`
3. Create and activate a virtual environment: `python -m venv .venv`, `.\.venv\scripts\activate`
4. Install `knowledge-storm`: `pip install knowledge-storm`
5. Install other requirements: `pip install -r requirements.txt`
6. Create a copy of `secrets.toml` and place it under `.streamlit/`.
7. Run `streamlit run storm.py`
```

Looks like it wants to run...
- ![image](https://github.com/user-attachments/assets/311104af-d5c6-41f4-97ee-fece091f6e95)

But instead errors-out...
- ![image](https://github.com/user-attachments/assets/76b1eb04-f404-4d0b-94ed-7d71914fd9b4)

**Error**:

```
2024-08-15 15:32:58.001 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\storm.py", line 6, in <module>   
    import demo_util
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\demo_util.py", line 16, in <module>
    from knowledge_storm import STORMWikiRunnerArguments, STORMWikiRunner, STORMWikiLMConfigs
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\knowledge_storm\__init__.py", line 1, in <module>
    from .storm_wiki.engine import (
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\knowledge_storm\storm_wiki\__init__.py", line 1, in <module>
    from .engine import *
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\knowledge_storm\storm_wiki\engine.py", line 9, in <module>
    from .modules.article_generation import StormArticleGenerationModule
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\knowledge_storm\storm_wiki\modules\__init__.py", line 1, in <module>
    from .knowledge_curation import *
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\knowledge_storm\storm_wiki\modules\knowledge_curation.py", line 11, in <module>
    from .storm_dataclass import DialogueTurn, StormInformationTable, StormInformation
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\knowledge_storm\storm_wiki\modules\storm_dataclass.py", line 11, in <module>
    from ...utils import ArticleTextProcessing, FileIOHelper
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\knowledge_storm\utils.py", line 19, in <module>
    from trafilatura import extract
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\trafilatura\__init__.py", line 18, in <module>
    from .core import bare_extraction, extract, process_record
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\trafilatura\core.py", line 16, in <module>
    from .external import compare_extraction
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\trafilatura\external.py", line 9, in <module>
    from justext.core import (ParagraphMaker, classify_paragraphs,
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\justext\__init__.py", line 12, in <module>
    from .core import justext
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\justext\core.py", line 21, in <module>
    from lxml.html.clean import Cleaner
  File "C:\Users\redacto\Documents\projects\storm\frontend\demo_light\.venv\Lib\site-packages\lxml\html\clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```

**To Reproduce**
See above

**Screenshots**
See above

**Environment:**
 - **OS**: Windows 11
 - **Browser**: Chrome

**Comment by ericthomas1** [comment]
`pip install lxml_html_clean` fixed the issue.
