### ISSUE TITLE
[BUG] knowledge_storm 0.2.5 doesn't contain TavilySearchRM in rm.py?

### ISSUE THREAD

**Issue by danieldekay** [stanford-oval/storm#171]
**Describe the bug**
Can't run examples locally using the packaged knowledge_storm as TavilySearchRM is not included in the package.

**To Reproduce**
1. Clone repository
2. pip install  -r requirements.txt`
3. python ./examples/run_storm_wiki_gpt.py --retriever you --do-research --do-generate-outline --search-top-k 10 --do-generate-article

```
Traceback (most recent call last):
  File "/mnt/c/Users/UserName/Develop/_external_sources/storm/./examples/run_storm_wiki_gpt.py", line 26, in <module>
    from knowledge_storm.rm import YouRM, BingSearch, BraveRM, SerperRM, DuckDuckGoSearchRM, TavilySearchRM, SearXNG
ImportError: cannot import name 'TavilySearchRM' from 'knowledge_storm.rm' (/home/kaesmad/Envs/storm/lib/python3.11/site-packages/knowledge_storm/rm.py)
```

**Environment:**
System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Fri Mar 29 23:14:13 UTC 2024
> Python Version:  3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.3.0
> langsmith: 0.1.121
> langchain_huggingface: 0.1.0
> langchain_qdrant: 0.1.4
> langchain_text_splitters: 0.3.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> fastembed: Installed. No version info available.
> httpx: 0.27.0
> huggingface-hub: 0.24.5
> jsonpatch: 1.33
> orjson: 3.10.6
> packaging: 23.2
> pydantic: 2.8.2
> PyYAML: 6.0.1
> qdrant-client: 1.11.2
> requests: 2.32.3
> sentence-transformers: 3.1.0
> tenacity: 8.5.0
> tokenizers: 0.19.1
> transformers: 4.43.3
> typing-extensions: 4.12.2

**Comment by alexmanner** [comment]
I get the same error on macos:

(Storm_1) user@machine storm % python examples/run_storm_wiki_gpt.py \
    --output-dir $OUTPUT_DIR \
    --retriever you \
    --do-research \
    --do-generate-outline \
    --do-generate-article \
    --do-polish-article
Traceback (most recent call last):
  File "/path/to/run_storm_wiki_gpt.py", line 26, in <module>
    from knowledge_storm.rm import YouRM, BingSearch, BraveRM, SerperRM, DuckDuckGoSearchRM, TavilySearchRM, SearXNG
ImportError: cannot import name 'TavilySearchRM' from 'knowledge_storm.rm' (/path/to/knowledge_storm/rm.py)

**Comment by shaoyijia** [comment]
Thanks for reporting this! I just bumped up the pypi package version. The issue shall be resolved if you run `pip install knowledge-storm --upgrade`.

**Comment by alexmanner** [comment]
Many thanks for your quick support, this works now.
