### ISSUE TITLE
[BUG] 我在使用vllm时，出现了openai的错误，某些请求也是通过openai接口发出的吗？run_storm_wiki_mistral.py

### ISSUE THREAD

**Issue by ZepengDu** [stanford-oval/storm#248]
Topic: AI
openai._base_client : INFO     : Retrying request to /chat/completions in 0.464737 seconds
openai._base_client : INFO     : Retrying request to /chat/completions in 0.963437 seconds
Failed to generate completion: Connection error.
Traceback (most recent call last):
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpcore/_sync/http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/openai/_base_client.py", line 990, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/lm.py", line 677, in __call__
    response = self.request(prompt, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/lm.py", line 649, in request
    return self.basic_request(prompt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/lm.py", line 635, in basic_request
    completion = self.client.chat.completions.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 829, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/openai/_base_client.py", line 1014, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/openai/_base_client.py", line 1092, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/openai/_base_client.py", line 1014, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/openai/_base_client.py", line 1092, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/openai/_base_client.py", line 1024, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/flyvideo/mySata/dzp/storm/examples/storm_examples/run_storm_wiki_mistral.py", line 190, in <module>
    main(parser.parse_args())
  File "/home/flyvideo/mySata/dzp/storm/examples/storm_examples/run_storm_wiki_mistral.py", line 141, in main
    runner.run(
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/storm_wiki/engine.py", line 394, in run
    information_table = self.run_knowledge_curation_module(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/interface.py", line 499, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/storm_wiki/engine.py", line 219, in run_knowledge_curation_module
    self.storm_knowledge_curation_module.research(
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/storm_wiki/modules/knowledge_curation.py", line 372, in research
    considered_personas = self._get_considered_personas(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/storm_wiki/modules/knowledge_curation.py", line 282, in _get_considered_personas
    return self.persona_generator.generate_persona(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/storm_wiki/modules/persona_generator.py", line 151, in generate_persona
    personas = self.create_writer_with_persona(topic=topic)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/dspy/primitives/program.py", line 26, in __call__
    return self.forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/storm_wiki/modules/persona_generator.py", line 80, in forward
    related_topics = self.find_related_topic(topic=topic).related_topics
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/dspy/predict/predict.py", line 61, in __call__
    return self.forward(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/dspy/predict/chain_of_thought.py", line 59, in forward
    return super().forward(signature=signature, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/dspy/predict/predict.py", line 103, in forward
    x, C = dsp.generate(template, **config)(x, stage=self.stage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/dsp/primitives/predict.py", line 77, in do_generate
    completions: list[dict[str, Any]] = generator(prompt, **kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/flyvideo/anaconda3/envs/dzp-storm/lib/python3.11/site-packages/knowledge_storm/lm.py", line 680, in __call__
    raise Exception(e)
Exception: Connection error.

**Comment by Yucheng-Jiang** [comment]
If no more updates in this thread, will close the issue soon.
