### ISSUE TITLE
[BUG] Uncaught Exception

### ISSUE THREAD

**Issue by ZillionsAI** [stanford-oval/storm#262]
Received the following ERROR
**Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_**

Specificially

`Traceback (most recent call last):
  File "/opt/anaconda3/envs/storm/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/opt/anaconda3/envs/storm/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/ZillionsInternational/Desktop/storm/frontend/demo_light/storm.py", line 62, in <module>
    main()
  File "/Users/ZillionsInternational/Desktop/storm/frontend/demo_light/storm.py", line 58, in main
    CreateNewArticle.create_new_article_page()
  File "/Users/ZillionsInternational/Desktop/storm/frontend/demo_light/pages_util/CreateNewArticle.py", line 113, in create_new_article_page
    handle_initiated()
  File "/Users/ZillionsInternational/Desktop/storm/frontend/demo_light/pages_util/CreateNewArticle.py", line 46, in handle_initiated
    demo_util.set_storm_runner()
  File "/Users/ZillionsInternational/Desktop/storm/frontend/demo_light/demo_util.py", line 507, in set_storm_runner
    llm_configs.init_openai_model(openai_api_key=st.secrets['OPENAI_API_KEY'], openai_type='openai')
TypeError: STORMWikiLMConfigs.init_openai_model() missing 1 required positional argument: 'azure_api_key'`

**Comment by jaydeep-mbarc** [comment]
I fix this by setting up azure_api_key as optional parameter [here](https://github.com/stanford-oval/storm/pull/268)

**Comment by BBC-Esq** [comment]
I think that you can set the api key within the secrets.toml file that you should be creating.  Let me know if this solves the issue?

**Comment by Chessing234** [comment]
PR makes azure_api_key optional on init_openai_model so the openai-only demo path works.
