### ISSUE TITLE
conversation_log.json not created

### ISSUE THREAD

**Issue by jacb9** [stanford-oval/storm#31]
Troubleshooting suggestions? thanks.

Traceback (most recent call last):
  File "C:\Users\...\Desktop\storm-main\storm-main\scripts\run_storm_wiki_gpt.py", line 111, in <module>
    main(parser.parse_args())
  File "C:\Users\...\Desktop\storm-main\storm-main\scripts\run_storm_wiki_gpt.py", line 68, in main
    runner.run(
  File "C:\Users\...\Desktop\storm-main\storm-main\src\storm_wiki\engine.py", line 286, in run
    information_table = StormInformationTable.from_conversation_log_file(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\Desktop\storm-main\storm-main\src\storm_wiki\modules\storm_dataclass.py", line 145, in from_conversation_log_file
    conversation_log_data = FileIOHelper.load_json(path)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\Desktop\storm-main\storm-main\src\utils.py", line 302, in load_json
    with open(file_name, 'r', encoding=encoding) as fr:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './results/gpt\\newtest\\conversation_log.json'

**Comment by Yucheng-Jiang** [comment]
Hi, could you provide the command you’re trying to run?

**Comment by jacb9** [comment]
C:\Users\...\Desktop\storm-main\storm-main>python scripts\run_storm_wiki_gpt.py
Topic: newtest

The results directory "newtest" is created, but empty.

**Comment by Yucheng-Jiang** [comment]
It's expected behavior. You have to manually set command line arguments to define which stages of the pipeline you're planning to run. We declare these arguments [here](https://github.com/stanford-oval/storm/blob/5d21c393e64d8c877ae6a9db3a0df0a72a926b33/examples/run_storm_wiki_gpt.py#L91-L99).

If you're going to run all stages of the pipeline, these arguments are needed `--do-research --do-generate-outline --do-generate-article`. You may want to add `--do-polish-article` if you hope to add summary / lead section of the article, and `--remove-duplicate` if hope to remove duplicate contents across different sections (this may lead to higher costs and much longer running time).

**Comment by jacb9** [comment]
Thank you. I thought the run_storm prompt set the default as true. Appears to be running now. Looking forward to exploring storm's capabilities.

**Comment by jacb9** [comment]
Thanks again.

Getting further -- storm_gen_outline.txt, conversation_log.json, direct_gen_outline.txt, and raw_search_results.json all created and look promising, but tripping up after that (see below). Will see if I can get further tomorrow…

Best regards, Joel

C:\Users\baum\Desktop\storm-main\storm-main>python scripts\run_storm_wiki_gpt.py --do-research --do-generate-outline --do-generate-article --do-polish-article --remove-duplicate
Topic: vancouver island beaches
Traceback (most recent call last):
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1042, in _create
    self.do_handshake()
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1042, in _create
    self.do_handshake()
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\baum\Desktop\storm-main\storm-main\scripts\run_storm_wiki_gpt.py", line 118, in <module>
    main(parser.parse_args())
  File "C:\Users\baum\Desktop\storm-main\storm-main\scripts\run_storm_wiki_gpt.py", line 75, in main
    runner.run(
  File "C:\Users\baum\Desktop\storm-main\storm-main\src\storm_wiki\engine.py", line 301, in run
    draft_article = self.run_article_generation_module(outline=outline,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\Desktop\storm-main\storm-main\src\interface.py", line 376, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\Desktop\storm-main\storm-main\src\storm_wiki\engine.py", line 210, in run_article_generation_module
    draft_article = self.storm_article_generation.generate_article(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\Desktop\storm-main\storm-main\src\storm_wiki\modules\article_generation.py", line 56, in generate_article
    information_table.prepare_table_for_retrieval()
  File "C:\Users\baum\Desktop\storm-main\storm-main\src\storm_wiki\modules\storm_dataclass.py", line 154, in prepare_table_for_retrieval
    self.encoder = SentenceTransformer('paraphrase-MiniLM-L6-v2')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 205, in __init__
    modules = self._load_auto_model(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 1197, in _load_auto_model
    transformer_model = Transformer(
                        ^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentence_transformers\models\Transformer.py", line 36, in __init__
    self._load_model(model_name_or_path, config, cache_dir, **model_args)
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentence_transformers\models\Transformer.py", line 65, in _load_model
    self.auto_model = AutoModel.from_pretrained(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\modeling_utils.py", line 3306, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\utils\hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py", line 1492, in hf_hub_download
    http_get(
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py", line 456, in http_get
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py", line 392, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\utils\_http.py", line 68, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baum\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)), '(Request ID: f12616cb-18d0-4bda-8782-4bb46510b2a2)')

**Comment by Octobot222** [comment]
Hey guys sorry for the delay

**Comment by Yucheng-Jiang** [comment]
@jacb9 We haven't ran into this problem before. Here's some related posts I find.
1. https://github.com/RallyTools/RallyRestToolkitForPython/issues/179
2. https://stackoverflow.com/questions/50771343/python3-requests-connectionreseterror10054-when-opening-a-picture

I suspect it has something to do with your proxy configuration. 

This line is raising the error
```bash
  File "{root}\storm-main\storm-main\src\storm_wiki\modules\storm_dataclass.py", line 154, in prepare_table_for_retrieval
    self.encoder = SentenceTransformer('paraphrase-MiniLM-L6-v2')
```
A quick workaround is to download this model to local filesystem and import the model locally.

**Comment by jacb9** [comment]
Thanks.

Download which model? (Module?) From where?


On Apr 25, 2024 7:23 a.m., Yucheng-Jiang ***@***.***> wrote:
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@jacb9<https://github.com/jacb9> We haven't ran into this problem before. Here's some related posts I find.

  1.  RallyTools/RallyRestToolkitForPython#179<https://github.com/RallyTools/RallyRestToolkitForPython/issues/179>
  2.  https://stackoverflow.com/questions/50771343/python3-requests-connectionreseterror10054-when-opening-a-picture

I suspect it has something to do with your proxy configuration.

This line is raising the error

  File "{root}\storm-main\storm-main\src\storm_wiki\modules\storm_dataclass.py", line 154, in prepare_table_for_retrieval
    self.encoder = SentenceTransformer('paraphrase-MiniLM-L6-v2')

A quick workaround is to download this model to local filesystem and import the model locally.

**Comment by Yucheng-Jiang** [comment]
@jacb9 sentence transformer `paraphrase-MiniLM-L6-v2` from hugging face.
